Obs matrix work
hpc4cmb/toast pull request #670
Opened 2023-05-24 21:49 UTC by keskitalo

Support for writing out noise-weighted observation matrices for rapid co-adding.

2023-06-02 22:02 UTC, keskitalo commented
Unit test added and passes.

2023-06-06 18:06 UTC, tskisner requested changes
Looks good, just need to add the missing entry point and check out whether there is a typo or missing file (or tell me what I missed).

2023-06-06 18:06 UTC, tskisner commented on src/toast/tests/ops_filterbin.py
> +            fname_matrix = ops.combine_observation_matrix(rootname)
I don't see where this is defined in the `toast.ops` module.  Maybe a typo or a file is not committed?

2023-06-06 19:34 UTC, keskitalo commented on src/toast/_libtoast/todmap_mapmaker.cpp
> +void add_matrix(
Changed the name

2023-06-06 19:34 UTC, keskitalo commented on src/toast/scripts/CMakeLists.txt
> +    toast_obsmatrix_coadd.py
Added

2023-06-06 19:35 UTC, keskitalo commented on src/toast/tests/ops_filterbin.py
> +                fname_matrix = ops.combine_observation_matrix(rootname)
see above

2023-06-06 19:38 UTC, tskisner commented on src/toast/tests/ops_filterbin.py
> +            fname_matrix = ops.combine_observation_matrix(rootname)
Sorry, completely missed that import in `toast.ops.__init__.py`!

2023-06-06 19:39 UTC, keskitalo commented
Accidentally applied the corrections to the `toast3` branch. Rebased this to match.

2023-06-06 19:39 UTC, tskisner approved these changes
Thanks for the fixes!

2023-06-16 06:22 UTC, keskitalo commented
Merging the approved PR now that all of the CI tests pass.

2023-06-16 06:22 UTC, merged