Interpolate healpix maps
hpc4cmb/toast pull request #784
Opened 2024-08-29 00:42 UTC by keskitalo

Add an operator that uses bilinear interpolation to generate continuous scanned signal from a HEALPix map. The maps are stored in node shared memory to reduce the required memory.

When scanning and co-adding multiple maps, they may be of different resolutions and some or all interpolated maps may be unpolarized.

2024-09-24 12:28 UTC, tskisner requested changes
Looks good, just a couple of small changes.

2024-09-24 21:04 UTC, keskitalo commented on src/toast/ops/interpolate_healpix.py
> +    )
Thanks!

2024-09-24 21:05 UTC, keskitalo commented on src/toast/ops/interpolate_healpix.py
> +        detdata_keys = self.det_data.split(";")
Done.

2024-09-24 21:11 UTC, keskitalo commented on src/toast/ops/interpolate_healpix.py
> +                weights = ob.detdata[self.stokes_weights.weights][det]
That was sloppy, I agree. Fixed. `ref` should still reference the parent observation.

2024-09-25 13:06 UTC, tskisner approved these changes

2024-09-25 14:18 UTC, keskitalo commented on src/toast/ops/interpolate_healpix.py
> +    )
Thanks! Removed.

2024-09-25 14:19 UTC, merged